events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name mysafety24x7.in www.mysafety24x7.in;

        # SOCKET SUPPORT
        location /socket.io/ {
            proxy_pass http://mysafety-backend:4000/socket.io/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        # BACKEND API
        location /api/ {
            proxy_pass http://mysafety-backend:4000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        # TEMP ROOT
        location / {
            return 200 "mysafety nginx is running (HTTP). Backend: /api/\n";
            add_header Content-Type text/plain;
        }
    }
}
